spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:video_catalog_db;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    username: root
    password: 123456
  h2:
    console:
      enabled: true
      path: /h2