spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://127.0.0.1:33006/video-catalog?serverTimezone=UTC}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: ${DATABASE_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: ${DATABASE_SHOW_SQL:true}
  logging:
    level:
      org:
        hibernate:
          SQL: ${LOGGING_LEVEL_HIBERNATE:true}