version: '3'

services:
  db:
    container_name: video-catalog-db
    image: mariadb:10.5.8
    tty: true
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=video-catalog
    ports:
      - 33006:3306
    volumes:
        - ./db/dbdata:/var/lib/mysql